# Generated by Django 3.2.7 on 2021-10-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_author_recipename',
        ),
    ]
